site_name: WingramOrg
site_url: https://wingram.org
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.prune
    
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share

    - content.code.copy
    
  palette:
    scheme: slate
    primary: custom
    accent: custom
plugins:
  - search
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/codegram01
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@WingramOrg
    - icon: fontawesome/brands/telegram 
      link: https://t.me/WingramOrg
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/WingramOrg
    - icon: material/email
      link: mailto:wingram.contact@gmail.com
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: "You can forget this site, but you can't forget an Ideology"