site_name: WingramOrg
site_url: https://wingram.org
# repo_url: https://github.com/codegram01/WingramOrg
# repo_name: ""
# edit_uri: edit/main/src/
docs_dir: src
site_dir: docs
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil 
    view: material/eye
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - navigation.tabs
    - header.autohide
    # - navigation.tabs.sticky
    
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share

    - content.code.copy
    # - content.action.edit
    # - content.action.view
    
  palette:
    scheme: slate
    primary: custom
    accent: custom
plugins:
  - search
  - tags:
      tags_file: tags.md 
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/codegram01
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@WingramOrg
    - icon: fontawesome/brands/telegram 
      link: https://t.me/WingramOrg
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/WingramOrg
    - icon: material/email
      link: mailto:wingram.contact@gmail.com
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: "You can forget this site, but you can't forget an Ideology"
